import { BaseSeeder } from '@adonisjs/lucid/seeders'
import Type from '#models/type'
import { TextFormatter } from '#utils/text_formatter'

export default class TypeSeeder extends BaseSeeder {
  async run() {
    // category = ['default', 'formation', 'evaluation', 'document', 'identity', 'department']
    // target_guard = ['default', 'admin', 'teacher', 'student', 'shared']
    // visibility = ['default', 'public', 'private', 'internal']

    const dataInsert = [
      {
        // id: 1,
        name: `Diplôme`,
        slug: TextFormatter.getTextSlug(`Diplôme`),
        description: `Diplôme délivré par l'institution`,
        category: 'formation' as 'formation',
        target_guard: 'shared' as 'shared',
        visibility: 'public' as 'public',
      },
      {
        // id: 2,
        name: `Formation`,
        slug: TextFormatter.getTextSlug(`Formation`),
        description: `Formation personnalisée`,
        category: 'formation' as 'formation',
        target_guard: 'shared' as 'shared',
        visibility: 'public' as 'public',
      },
      {
        // id: 3,
        name: `Certification`,
        slug: TextFormatter.getTextSlug(`Certification`),
        description: `Certification obtenue après une formation`,
        category: 'formation' as 'formation',
        target_guard: 'shared' as 'shared',
        visibility: 'public' as 'public',
      },
      {
        // id: 4,
        name: `Contrôle Continu N°1`,
        slug: TextFormatter.getTextSlug(`Contrôle Continu N°1`),
        abbr: `CC1`,
        description: ``,
        category: 'evaluation' as 'evaluation',
        target_guard: 'shared' as 'shared',
        visibility: 'public' as 'public',
      },
      {
        // id: 5,
        name: `Contrôle Continu N°2`,
        slug: TextFormatter.getTextSlug(`Contrôle Continu N°2`),
        abbr: `CC2`,
        description: ``,
        category: 'evaluation' as 'evaluation',
        target_guard: 'shared' as 'shared',
        visibility: 'public' as 'public',
      },
      {
        // id: 6,
        name: `Contrôle Continu N°3`,
        slug: TextFormatter.getTextSlug(`Contrôle Continu N°3`),
        abbr: `CC3`,
        description: ``,
        category: 'evaluation' as 'evaluation',
        target_guard: 'shared' as 'shared',
        visibility: 'public' as 'public',
      },
      {
        // id: 7,
        name: `Contrôle Continu N°4`,
        slug: TextFormatter.getTextSlug(`Contrôle Continu N°4`),
        abbr: `CC4`,
        description: ``,
        category: 'evaluation' as 'evaluation',
        target_guard: 'shared' as 'shared',
        visibility: 'public' as 'public',
      },
      {
        // id: 8,
        name: `Examen Théorique`,
        slug: TextFormatter.getTextSlug(`Examen Théorique`),
        abbr: `ExamTh`,
        description: ``,
        category: 'evaluation' as 'evaluation',
        target_guard: 'shared' as 'shared',
        visibility: 'public' as 'public',
      },
      {
        // id: 9,
        name: `Examen Pratique`,
        slug: TextFormatter.getTextSlug(`Examen Pratique`),
        abbr: `ExamPr`,
        description: ``,
        category: 'evaluation' as 'evaluation',
        target_guard: 'shared' as 'shared',
        visibility: 'public' as 'public',
      },
      {
        // id: 10,
        name: `PFA`,
        slug: TextFormatter.getTextSlug(`PFA`),
        abbr: `PFA`,
        description: `Projet de Fin d'Année`,
        category: 'evaluation' as 'evaluation',
        target_guard: 'shared' as 'shared',
        visibility: 'public' as 'public',
      },
      {
        // id: 11,
        name: `PFE`,
        slug: TextFormatter.getTextSlug(`PFE`),
        abbr: `PFE`,
        description: `Projet de Fin d'Etude`,
        category: 'evaluation' as 'evaluation',
        target_guard: 'shared' as 'shared',
        visibility: 'public' as 'public',
      },
      {
        // id: 12,
        name: `Stage I`,
        slug: TextFormatter.getTextSlug(`Stage I`),
        abbr: `Stage I`,
        description: ``,
        category: 'evaluation' as 'evaluation',
        target_guard: 'shared' as 'shared',
        visibility: 'public' as 'public',
      },
      {
        // id: 13,
        name: `Stage II`,
        slug: TextFormatter.getTextSlug(`Stage II`),
        abbr: `Stage II`,
        description: ``,
        category: 'evaluation' as 'evaluation',
        target_guard: 'shared' as 'shared',
        visibility: 'public' as 'public',
      },
      {
        // id: 14,
        name: `Département Informatique`,
        slug: TextFormatter.getTextSlug(`Département Informatique`),
        abbr: `D-Info`,
        description: `Enseignement du développement logiciel, de la programmation, des bases de données et des systèmes informatiques.`,
        category: 'department' as 'department',
        target_guard: 'shared' as 'shared',
        visibility: 'public' as 'public',
      },
      {
        // id: 15,
        name: `Département Systèmes et Réseaux`,
        slug: TextFormatter.getTextSlug(`Département Systèmes et Réseaux`),
        abbr: `D-SR`,
        description: `Formation en infrastructure réseau, systèmes d’exploitation, cybersécurité et administration système.`,
        category: 'department' as 'department',
        target_guard: 'shared' as 'shared',
        visibility: 'public' as 'public',
      },
      {
        // id: 16,
        name: `Département Sécurité Informatique`,
        slug: TextFormatter.getTextSlug(`Département Sécurité Informatique`),
        abbr: `D-SI`,
        description: `Spécialisé dans la protection des systèmes d’information, la cybersécurité et les audits techniques.`,
        category: 'department' as 'department',
        target_guard: 'shared' as 'shared',
        visibility: 'public' as 'public',
      },
      {
        // id: 17,
        name: `Département Finance et Comptabilité`,
        slug: TextFormatter.getTextSlug(`Département Finance et Comptabilité`),
        abbr: `D-FC`,
        description: `Couvre la gestion financière, l’analyse comptable, la fiscalité et le contrôle de gestion.`,
        category: 'department' as 'department',
        target_guard: 'shared' as 'shared',
        visibility: 'public' as 'public',
      },
      {
        // id: 18,
        name: `Département Commerce et Marketing`,
        slug: TextFormatter.getTextSlug(`Département Commerce et Marketing`),
        abbr: `D-CM`,
        description: `Aborde les techniques de vente, la communication commerciale, le marketing digital et la négociation.`,
        category: 'department' as 'department',
        target_guard: 'shared' as 'shared',
        visibility: 'public' as 'public',
      },
      {
        // id: 19,
        name: `Département Gestion des Entreprises`,
        slug: TextFormatter.getTextSlug(`Département Gestion des Entreprises`),
        abbr: `D-GE`,
        description: `Forme aux pratiques de management, de stratégie et de gestion organisationnelle.`,
        category: 'department' as 'department',
        target_guard: 'shared' as 'shared',
        visibility: 'public' as 'public',
      },
      {
        // id: 20,
        name: `Département Management de Projet`,
        slug: TextFormatter.getTextSlug(`Département Management de Projet`),
        abbr: `D-MP`,
        description: `Prépare à la planification, la gestion d’équipe, la gestion budgétaire et les outils de pilotage.`,
        category: 'department' as 'department',
        target_guard: 'shared' as 'shared',
        visibility: 'public' as 'public',
      },
      {
        // id: 21,
        name: `Département Transport et Logistique`,
        slug: TextFormatter.getTextSlug(`Département Transport et Logistique`),
        abbr: `D-TL`,
        description: `Concerne la gestion de la chaîne logistique, la logistique internationale et le transport de marchandises.`,
        category: 'department' as 'department',
        target_guard: 'shared' as 'shared',
        visibility: 'public' as 'public',
      },
      {
        // id: 22,
        name: `Département Ressources Humaines`,
        slug: TextFormatter.getTextSlug(`Département Ressources Humaines`),
        abbr: `D-RH`,
        description: `Spécialisé dans la gestion du personnel, le droit du travail et le développement des compétences.`,
        category: 'department' as 'department',
        target_guard: 'shared' as 'shared',
        visibility: 'public' as 'public',
      },
      {
        // id: 23,
        name: `Département Langues et Communication`,
        slug: TextFormatter.getTextSlug(`Département Langues et Communication`),
        abbr: `D-LC`,
        description: `Développe les compétences linguistiques et communicationnelles pour le monde professionnel.`,
        category: 'department' as 'department',
        target_guard: 'shared' as 'shared',
        visibility: 'public' as 'public',
      },
    ]

    for (const item of dataInsert) {
      await Type.updateOrCreate({ name: item.name, slug: item.slug, category: item.category }, item)
    }

    console.log('***** TypeSeeder Executed *****')
  }
}
